server:
  port: 8081

spring:
  application:
    name: ms-diners
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cat
    password: 123$%^qwe
    url: jdbc:mysql://rm-bp1i64x1vq836b3tdoo.mysql.rds.aliyuncs.com:3306/db_immoc?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
  # Redis
  redis:
    # 启用哨兵模式以后无需直接连接 Redis，通过哨兵可以获得主从信息
    port: 6379
    host: 120.79.159.223
    timeout: 3000 # 连接超时时间
    password: 123456 # Redis 服务器密码
    database: 1
  # swagger
  swagger:
    base-package: com.imooc.diners
    title: 美食社交食客API接口文档


# Oauth2 客户端信息
oauth2:
  client:
    client-id: appId
    secret: 123456
    grant_type: password
    scope: api

# oauth2 服务地址
service:
  name:
    ms-oauth-server: http://ms-oauth2-server/
    ms-points-server: http://ms-points-server/

#eureka 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

# Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

logging:
  pattern:
    console: '%d{2100-01-01 13:14:00.666} [%thread] %-5level %logger{50} - %msg%n'