server:
  port: 8080

spring:
  application:
    name: ms-registry

#eureka 注册中心
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka/